FreeMountainTest/Models/Response.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FreeMountainTest.Models
{
    [Table("RESPONSES")]
    public class Response
    {
        [Key]
        [Required]
        [StringLength(12, ErrorMessage = "Response Code is a required field.")]
        [DisplayName("Response Code")]
        [Column("RESPONSE_CODE")]
        public string ResponseCode { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Response Description is a required field.")]
        [DisplayName("Response Description")]
        [Column("RESPONSE_DESCRIPTION")]
        public string ResponseDescription { get; set; }
        [Column("RESPONSE_TYPE")]
        [StringLength(20)]
        [DisplayName("Response Type")]
        public string ResponseType { get; set; }
        [Column("PROMOTION")]
        [StringLength(20)]
        public string Promotion { get; set; }
        [Column("CHANNEL")]
        [StringLength(5)]
        public string Channel { get; set; }
        [Column("START_DATE", TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column("END_DATE", TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column("LAST_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? LastUpdateDate { get; set; }
        [Column("STATUS")]
        [StringLength(1)]
        public string Status { get; set; }
    }
}

FreeMountainTest/Controllers/ResponseController.cs
using FreeMountainTest.Data;
using FreeMountainTest.Models;
using FreeMountainTest.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FreeMountainTest.Controllers
{
    public class ResponseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ResponseController(ApplicationDbContext db)
        {
            _db = db;
        }

        //DISPLAYS RESPONSE DATA
        public IActionResult Index()
        {
            IEnumerable<Response> objList = _db.Response;
            return View(objList);
        }

        //GET-Add
        public IActionResult Add(string id)
        {
            //creating a new Response View Model to hold Response values, and SelectList values
            ResponseVM responseVM = new ResponseVM()
            {
                Response = new Response(),
                ChannelSelectList = _db.Response.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if (id == null)
            {
                //for create
                return View(responseVM);
            }
            else
            {
                responseVM.Response = _db.Response.Find(id);
                if (responseVM.Response == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
            }

            return View(responseVM);
        }

        //POST-Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(ResponseVM responseVM)
        {
            if (ModelState.IsValid)
            {
                if (_db.Response.Find(responseVM.Response.ResponseCode) == null)
                {
                    _db.Response.Add(responseVM.Response);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Select List
            responseVM.ChannelSelectList = _db.Response.Select(id => new SelectListItem
            {
                Text = id.Channel,
                Value = id.Channel.ToString()
            });
            return View(responseVM);
        }

        //GET-Update
        public IActionResult Update(string id)
        {
            //creating a new Response View Model to hold Response values, and SelectList values
            ResponseVM responseVM = new ResponseVM()
            {
                Response = new Response(),
                ChannelSelectList = _db.Response.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if(id == null)
            {
                //for create
                return View(responseVM);
            }
            else
            {
                responseVM.Response = _db.Response.Find(id);
                if(responseVM.Response == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
                return View(responseVM);
            }
        }

        //POST-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ResponseVM responseVM)
        {
            if(ModelState.IsValid)
            {
                var objFromDb = _db.Response.Select(u => u.ResponseCode == responseVM.Response.ResponseCode);

                if(objFromDb != null)
                {
                    _db.Response.Update(responseVM.Response);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            //Select List
            responseVM.ChannelSelectList = _db.Response.Select(id => new SelectListItem
            {
                Text = id.Channel,
                Value = id.Channel.ToString()
            });
            return View(responseVM);
        }

        //GET-Delete
        public IActionResult Delete(string id)
        {
            //creating a new Response View Model to hold Response values, and SelectList values
            ResponseVM responseVM = new ResponseVM()
            {
                Response = new Response(),
                ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if (id == null)
            {
                return View(responseVM);
            }
            else
            {
                responseVM.Response = _db.Response.Find(id);
                if (responseVM.Response == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
                return View(responseVM);
            }
        }

        //POST-Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(string id)
        {
            var obj = _db.Response.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Response.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreeMountainTest/Views/Response/Add.cshtml
@model FreeMountainTest.Models.ViewModels.ResponseVM

@{
    var title = "Create New Response";
}

<form method="post" enctype="multipart/form-data">
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="ps-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>Response Code</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.ResponseCode" class="form-control" />
                        <span asp-validation-for="Response.ResponseCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>Response Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.ResponseDescription" class="form-control" />
                        <span asp-validation-for="Response.ResponseDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Response.Channel"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Response.Channel" asp-items="@Model.ChannelSelectList" class="form-control">
                            <option disabled selected>--Select Channel--</option>
                        </select>
                        <span asp-validation-for="Response.Channel" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" onclick="return validateInput()" class="btn btn-primary w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-10"> <i class="fas fa-arrow-left"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 250
            });
        });

        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error!',
                    'Please upload an image!',
                    'error'
                )
                return false;
            }
            return true;
        }
    </script>
}

FreeMountainTest/Views/Response/Delete.cshtml
@model FreeMountainTest.Models.ViewModels.ResponseVM

<form method="post">

    <input asp-for="Response.ResponseCode" hidden />
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="text-info pl-3">Delete Response</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>RESPONSE_CODE</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.ResponseCode" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>RESPONSE_DESCRIPTION</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.ResponseDescription" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>CHANNEL</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.Channel" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger w-100">Delete</button>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

FreeMountainTest/Views/Response/Index.cshtml
@model IEnumerable<FreeMountainTest.Models.Response>

<div class="row pt-4 pb-4">
    <div class="col-6">
        <h2 class="pl-3">Response List</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Response" asp-action="Add" class="btn btn-primary">Create New Response</a>
    </div>
</div>

<div>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>
                        RESPONSE_CODE
                    </th>
                    <th>
                        RESPONSE_DESCRIPTION
                    </th>
                    <th>
                        CHANNEL
                    </th>
                    <th>
                        EDIT RESPONSE
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="25%">@obj.ResponseCode</td>
                    <td width="25%">@obj.ResponseDescription</td>
                    <td width="25%">@obj.Channel</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Response" asp-route-Id="@obj.ResponseCode" asp-action="Update" class="btn btn-primary mx-2">Edit</a>
                            <a asp-controller="Response" asp-route-Id="@obj.ResponseCode" asp-action="Delete" class="btn btn-primary mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
</div>

FreeMountainTest/Views/Response/Update.cshtml
@model FreeMountainTest.Models.ViewModels.ResponseVM

@{
    var title = "Edit Response";
}

<form method="post" enctype="multipart/form-data">
    <input asp-for="Response.ResponseCode" hidden />
    <div class="border p-3">
        <div class="col">         
        </div>
        <div class="mb-3 row">
            <h2 class="pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>RESPONSE_CODE</label>
                    </div>
                    <div class="col-8">
                        <input disabled asp-for="Response.ResponseCode" class="form-control" />
                        <span asp-validation-for="Response.ResponseCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>RESPONSE_DESCRIPTION</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Response.ResponseDescription" class="form-control" />
                        <span asp-validation-for="Response.ResponseDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>CHANNEL</label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Response.Channel" asp-items="@Model.ChannelSelectList" class="form-control">
                            <option disabled selected>--Select Channel--</option>
                        </select>
                        <span asp-validation-for="Response.Channel" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-primary w-50" style="margin-left: 6em" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-10"> <i class="fas fa-arrow-left"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
               height: 250
            });
        });

        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error!',
                    'Please upload an image!',
                    'error'
                )
                return false;
            }
            return true;
        }
    </script>
}