FreeMountainTest/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FreeMountainTest.Models
{
    [Table("CAMPAIGNS")]
    public partial class Campaign
    {
        [Key]
        [Column("MFID")]
        public string Mfid { get; set; }
        [Required]
        [Column("MFID_DESCRIPTION")]
        [StringLength(100)]
        public string MfidDescription { get; set; }
        [Required]
        [Column("PROMOTION")]
        [StringLength(9)]
        public string Promotion { get; set; }
        [Column("CLIENT")]
        [StringLength(10)]
        public string Client { get; set; }
        [Column("CHANNEL")]
        [StringLength(5)]
        public string Channel { get; set; }
        [Column("SEED_LIST")]
        public int? SeedList { get; set; }
        [Column("DTS_DATE", TypeName = "datetime")]
        public DateTime? DtsDate { get; set; }
        [Column("EXTRACT_DATE", TypeName = "datetime")]
        public DateTime? ExtractDate { get; set; }
        [Column("PRINT_VENDOR")]
        [StringLength(5)]
        public string PrintVendor { get; set; }
        [Column("WAVE")]
        [StringLength(20)]
        public string Wave { get; set; }
        [Column("EXTRACT_SQL")]
        public string ExtractSql { get; set; }
        [Column("AML_UNIVERSE")]
        [StringLength(10)]
        public string AmlUniverse { get; set; }
        [Column("STATUS")]
        [StringLength(1)]
        public string Status { get; set; }
        [Column("AV_REQUIRED")]
        [StringLength(1)]
        public string AvRequired { get; set; }
        [Column("ALLOW_RENTAL_LIST")]
        [StringLength(1)]
        public string AllowRentalList { get; set; }
        [Column("RECURRANCE")]
        [StringLength(1)]
        public string Recurrance { get; set; }
        [Column("ALERT_NUM")]
        [StringLength(20)]
        public string AlertNum { get; set; }
        [Column("REVISION_NUM")]
        [StringLength(20)]
        public string RevisionNum { get; set; }
        [Column("EXTRACT_VIEW")]
        [StringLength(255)]
        public string ExtractView { get; set; }
        [Column("HTML_LOCATION")]
        [StringLength(255)]
        public string HtmlLocation { get; set; }
        [Column("AMAZON_CODE")]
        [StringLength(1)]
        public string AmazonCode { get; set; }
        [Column("EMAIL_SUBJECT")]
        [StringLength(100)]
        public string EmailSubject { get; set; }
        [Column("ISCONSUMER")]
        [StringLength(1)]
        public string Isconsumer { get; set; }
        [Column("ISINFLUENCER")]
        [StringLength(1)]
        public string Isinfluencer { get; set; }
        [Column("WORK_FLOW")]
        [StringLength(1)]
        public string WorkFlow { get; set; }
        [Column("CUSTOMER_SEARCH")]
        [StringLength(1)]
        public string CustomerSearch { get; set; }
        [Column("SEQ_NUM")]
        public int SeqNum { get; set; }
    }
}

FreeMountainTest/Controllers/CampaignController.cs
using FreeMountainTest.Data;
using FreeMountainTest.Models;
using FreeMountainTest.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FreeMountainTest.Controllers
{
    public class CampaignController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CampaignController(ApplicationDbContext db)

        {
            _db = db;
        }

        //DISPLAYS CAMPAIGN DATA
        public IActionResult Index(string searchString)
        {
            IEnumerable<Campaign> objList = _db.Campaign;
            return View(objList);
        }

        //GET-Add
        public IActionResult Add(string id)
        {
            //creating a new Campaign View Model to hold Campaign values, and SelectList values
            CampaignVM campaignVM = new CampaignVM()
            {
                Campaign = new Campaign(),
                ClientSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Client,
                    Value = id.Client.ToString()
                }),

                ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if (id == null)
            {
                //for create
                return View(campaignVM);
            }
            else
            {
                campaignVM.Campaign = _db.Campaign.Find(id);
                if (campaignVM.Campaign == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
                return View(campaignVM);
            }
        }

        //POST-Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(CampaignVM campaignVM)
        {
            if (ModelState.IsValid)
            {
                //if the Mfid is non-existant, a campaign will be created
                if (_db.Campaign.Find(campaignVM.Campaign.Mfid) == null)
                {
                    _db.Campaign.Add(campaignVM.Campaign);
                }
                //saves the updated changes to the database
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Select Lists
            campaignVM.ClientSelectList = _db.Campaign.Select(id => new SelectListItem
            {
                Text = id.Client,
                Value = id.Client.ToString()
            });
            campaignVM.ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
            {
                Text = id.Channel,
                Value = id.Channel.ToString()
            });

            return View(campaignVM);
        }

        //GET-Update
        public IActionResult Update(string id)
        {
            //creating a new Campaign View Model to hold Campaign values, and SelectList values
            CampaignVM campaignVM = new CampaignVM()
            {
                Campaign = new Campaign(),
                ClientSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Client,
                    Value = id.Client.ToString()
                }),
                ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if (id == null)
            {
                //for create
                return View(campaignVM);
            }
            else
            {
                campaignVM.Campaign = _db.Campaign.Find(id);
                if (campaignVM.Campaign == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
                return View(campaignVM);
            }
        }

        //POST-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(CampaignVM campaignVM)
        {
            if (ModelState.IsValid)
            {
                //var objFromDb is created as an instance of Campaign. The following line selects the Campaign being updated, found by the ID.
                var objFromDb = _db.Campaign.Select(u => u.Mfid == campaignVM.Campaign.Mfid); 
                if (objFromDb != null)
                {
                    //updates in the database
                    _db.Campaign.Update(campaignVM.Campaign);
                }
                //saves the updated changes to the database
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Select Lists
            campaignVM.ClientSelectList = _db.Campaign.Select(id => new SelectListItem
            {
                Text = id.Client,
                Value = id.Client.ToString()
            });
            campaignVM.ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
            {
                Text = id.Channel,
                Value = id.Channel.ToString()
            });

            return View(campaignVM);
        }
        
        //GET-Delete
        public IActionResult Delete(string id)
        {
            //creating a new Campaign View Model to hold Campaign values, and SelectList values
            CampaignVM campaignVM = new CampaignVM()
            {
                Campaign = new Campaign(),
                ClientSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Client,
                    Value = id.Client.ToString()
                }),
                ChannelSelectList = _db.Campaign.Select(id => new SelectListItem
                {
                    Text = id.Channel,
                    Value = id.Channel.ToString()
                })
            };

            if (id == null)
            {
                return View(campaignVM);
            }
            else
            {
                campaignVM.Campaign = _db.Campaign.Find(id);
                if (campaignVM.Campaign == null)
                {
                    //if the ID searched is not found
                    return NotFound();
                }
                return View(campaignVM);
            }
        }

        //POST-Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(string id)
        {
            var obj = _db.Campaign.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Campaign.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreeMountainTest/Views/Campaign/Add.cshtml
@model FreeMountainTest.Models.ViewModels.CampaignVM

@{
    var title = "Create New Campaign";
}

<form method="post" enctype="multipart/form-data">
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="ps-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>MFID</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Mfid" class="form-control" />
                        <span asp-validation-for="Campaign.Mfid" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>MFID Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.MfidDescription" class="form-control" />
                        <span asp-validation-for="Campaign.MfidDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Client"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Campaign.Client" asp-items="@Model.ClientSelectList" class="form-control">
                            <option disabled selected>--Select Client--</option>
                        </select>
                        <span asp-validation-for="Campaign.Client" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Channel"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Campaign.Channel" asp-items="@Model.ChannelSelectList" class="form-control">
                            <option disabled selected>--Select Channel--</option>
                        </select>
                        <span asp-validation-for="Campaign.Channel" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Promotion"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Promotion" class="form-control" />
                        <span asp-validation-for="Campaign.Promotion" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" onclick="return validateInput()" class="btn btn-primary w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-10"> <i class="fas fa-arrow-left"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 250
            });
        });

        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error!',
                    'Please upload an image!',
                    'error'
                )
                return false;
            }
            return true;
        }
    </script>
}

FreeMountainTest/Views/Campaign/Delete.cshtml
@model FreeMountainTest.Models.ViewModels.CampaignVM

<form method="post">

    <input asp-for="Campaign.Mfid" hidden />
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="text-info pl-3">Delete Campaign</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Mfid"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Mfid" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.MfidDescription"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.MfidDescription" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Client"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Client" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Channel"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Channel" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Promotion"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Promotion" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger w-100">Delete</button>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

FreeMountainTest/Views/Campaign/Index.cshtml
@model IEnumerable<FreeMountainTest.Models.Campaign>

    <div class="row pt-4 pb-4">
        <div class="col-6">
            <h2 class="pl-3">Campaign List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Campaign" asp-action="Add" class="btn btn-primary">Create New Campaign</a>
        </div>
    </div>

<div>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>
                        MFID
                    </th>
                    <th>
                        MFID_DESCRIPTION
                    </th>
                    <th>
                        CLIENT
                    </th>
                    <th>
                        CHANNEL
                    </th>
                    <th>
                        EDIT CAMPAIGN
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="20%">@obj.Mfid</td>
                    <td width="20%">@obj.MfidDescription</td>
                    <td width="20%">@obj.Client</td>
                    <td width="20%">@obj.Channel</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Campaign" asp-route-Id="@obj.Mfid" asp-action="Update" class="btn btn-primary mx-2">Edit</a>
                            <a asp-controller="Campaign" asp-route-Id="@obj.Mfid" asp-action="Delete" class="btn btn-primary mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
</div>

FreeMountainTest/Views/Campaign/Update.cshtml
@model FreeMountainTest.Models.ViewModels.CampaignVM

@{
    var title = "Edit Campaign";
}

<form method="post" enctype="multipart/form-data">
    <input asp-for="Campaign.Mfid" hidden />
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>MFID</label>
                    </div>
                    <div class="col-8">
                        <input disabled asp-for="Campaign.Mfid" class="form-control" />
                        <span asp-validation-for="Campaign.Mfid" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label>MFID Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.MfidDescription" class="form-control" />
                        <span asp-validation-for="Campaign.MfidDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Client"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Campaign.Client" asp-items="@Model.ClientSelectList" class="form-control">
                            <option disabled selected>--Select Client--</option>
                        </select>
                        <span asp-validation-for="Campaign.Client" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Channel"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Campaign.Channel" asp-items="@Model.ChannelSelectList" class="form-control">
                            <option disabled selected>--Select Channel--</option>
                        </select>
                        <span asp-validation-for="Campaign.Channel" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Campaign.Promotion"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Campaign.Promotion" class="form-control" />
                        <span asp-validation-for="Campaign.Promotion" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-primary w-50" style="margin-left: 6em" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-10"> <i class="fas fa-arrow-left"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
               height: 250
            });
        });

        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error!',
                    'Please upload an image!',
                    'error'
                )
                return false;
            }
            return true;
        }
    </script>
}